### ISSUE TITLE
Password is not being copied to clipboard

### ISSUE THREAD

**Issue by TheDevBuggs** [Cyanic76/password-generator#1]
I tesed this a few times. But the password wasn't copied to the clipboard even though the system alert said "Successfully copied to clipboard".

- Choose the option with numbers and special characters

- Entered the desired password length (15)

- Selected show and Copy.

_Tested on Google Chrome
Keyboard app: Gboard_

**Comment by Cyanic76** [comment]
Is a pop-up shown when you press "Copy" ?

**Comment by Cyanic76** [comment]
Oh, you may have not clicked on "Click herr" button... I'm on Brave browser - Chrome, like Brave, is based on Chromium and copy function works on it

**Comment by TheDevBuggs** [comment]
Hi,

I just tested it, and it worked. Previously the Generate button wasn't visible for some reason.
