### ISSUE TITLE
Améliorer l'IU

### ISSUE THREAD

**Issue by LProgead** [Cyanic76/password-generator#2]
Actuellement, l'interface utilisateur est plate, sans aucune mise en forme.
Je pense que cela pourrait rebuter certains utilisateurs.
Un générateur de mot de passe s'adresse à tout le monde, alors qu'actuellement, certaines personnes pourraient se tourner vers d'autres outils à cause de ce manque de mise en forme.

**Comment by Cyanic76** [comment]
L'UI a été modifiée pour apporter un thème sombre et une meilleure lisibilité. Un changement a été apporté au niveau des boutons qui deviennent verts pendant une seconde quand vous y cliquez dessus (ne s'applique qu'à "Copier" et "Générer").

**Comment by LProgead** [comment]
En effet, le thème sombre rend mieux. Mais la police et l'alignement fait toujours vieux site x)

**Comment by Cyanic76** [comment]
La raison de la police faisant "vieux site" c'est que le site n'utilise pas une certaine police (comme Segoe UI, Roboto, Arial, Helvetica, etc).

**Comment by LProgead** [comment]
Oui, j’ai pu voir ça et forkant le projet. 
J’ai d’abord patch certains bugs. Je bosse sur l’UI ASAP.

**Comment by LProgead** [comment]
Ouais, ça rend mieux comme ça.
Je pense avoir fini de te faire chier sur ton projet x)

Je ne vois pas spécialement de bugs à patch, l'UI est bien, tout pour plaire ce password gen xD
